const skillOptions = [
  { value: "programming", label: "Programming" },
  { value: "design", label: "Design" },
  { value: "writing", label: "Writing" },
  { value: "communication", label: "Communication" },
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "sql", label: "SQL" },
  { value: "c", label: "C" },
  { value: "cplus", label: "C++" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "typescript", label: "TypeScript" },
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "vue", label: "Vue.js" },
  { value: "nodejs", label: "Node.js" },
  { value: "express", label: "Express.js" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "laravel", label: "Laravel" },
  { value: "spring", label: "Spring" },
  { value: "wordpress", label: "WordPress" },
  { value: "unity", label: "Unity" },
  { value: "unreal", label: "Unreal Engine" },
  { value: "photoshop", label: "Photoshop" },
  { value: "illustrator", label: "Illustrator" },
  { value: "indesign", label: "InDesign" },
  { value: "aftereffects", label: "After Effects" },
  { value: "sketchup", label: "SketchUp" },
  { value: "autocad", label: "AutoCAD" },
  { value: "writing", label: "Writing" },
  { value: "editing", label: "Editing" },
  { value: "copywriting", label: "Copywriting" },
  { value: "proofreading", label: "Proofreading" },
  { value: "contentstrategy", label: "Content Strategy" },
  { value: "publicspeaking", label: "Public Speaking" },
  { value: "negotiation", label: "Negotiation" },
  { value: "leadership", label: "Leadership" },
  { value: "timemanagement", label: "Time Management" },
  { value: "creativity", label: "Creativity" },
  { value: "problem-solving", label: "Problem Solving" },
  { value: "teamwork", label: "Teamwork" },
  { value: "adaptability", label: "Adaptability" },
  { value: "criticalthinking", label: "Critical Thinking" },
  { value: "emotionalintelligence", label: "Emotional Intelligence" },
  { value: "analytics", label: "Analytics" },
  { value: "datamining", label: "Data Mining" },
  { value: "machinelearning", label: "Machine Learning" },
  { value: "artificialintelligence", label: "Artificial Intelligence" },
  { value: "dataanalysis", label: "Data Analysis" },
  { value: "datavisualization", label: "Data Visualization" },
  { value: "businessanalysis", label: "Business Analysis" },
  { value: "marketresearch", label: "Market Research" },
  { value: "strategicplanning", label: "Strategic Planning" },
  { value: "financialmanagement", label: "Financial Management" },
  { value: "projectmanagement", label: "Project Management" },
  { value: "agilemethodology", label: "Agile Methodology" },
  { value: "scrum", label: "Scrum" },
  { value: "sales", label: "Sales" },
  { value: "marketing", label: "Marketing" },
  { value: "digitalmarketing", label: "Digital Marketing" },
  { value: "socialmedia", label: "Social Media" },
  { value: "contentmarketing", label: "Content Marketing" },
  { value: "emailmarketing", label: "Email Marketing" },
  { value: "searchengineoptimization", label: "Search Engine Optimization" },
  { value: "userexperience", label: "User Experience (UX)" },
  { value: "userinterface", label: "User Interface (UI)" },
  { value: "webdesign", label: "Web Design" },
  { value: "uxresearch", label: "UX Research" },
  { value: "prototyping", label: "Prototyping" },
  { value: "wireframing", label: "Wireframing" },
  { value: "frontenddevelopment", label: "Frontend Development" },
  { value: "backenddevelopment", label: "Backend Development" },
  { value: "fullstackdevelopment", label: "Full Stack Development" },
  { value: "devops", label: "DevOps" },
  { value: "cloudcomputing", label: "Cloud Computing" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "blockchain", label: "Blockchain" },
  { value: "iot", label: "Internet of Things (IoT)" },
  { value: "virtualreality", label: "Virtual Reality" },
  { value: "augmentedreality", label: "Augmented Reality" },
  { value: "videography", label: "Videography" },
  { value: "photography", label: "Photography" },
  { value: "musicproduction", label: "Music Production" },
  { value: "soundengineering", label: "Sound Engineering" },
  { value: "animation", label: "Animation" },
  { value: "gamedesign", label: "Game Design" },
  { value: "graphicdesign", label: "Graphic Design" },
  { value: "illustration", label: "Illustration" },
  { value: "dataentry", label: "Data Entry" },
  { value: "administrativetasks", label: "Administrative Tasks" },
  { value: "customerservice", label: "Customer Service" },
  { value: "retail", label: "Retail" },
  { value: "logistics", label: "Logistics" },
];
export default skillOptions;
